@ReverseProxy_HostAddress = http://localhost:5270

GET {{ReverseProxy_HostAddress}}/index.json
Accept: application/json

HTTP/1.1 404  - Not Found
connection: close
date: Fri, 05 Jul 2024 14:52:45 GMT
server: Kestrel
transfer-encoding: chunked